export const users = [
   {"id": 1, "name": "Eghise Manukyan", "email": "manukyaneghishe@gmail.com", "rate":0.1, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 2, "name": "Erik Manukyan", "email": "dfgfgdfg@gmail.com", "rate":0.01, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 3, "name": "Johnn Garcia", "email": "yuttrdgdf@gmail.com", "rate":0.2, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 4, "name": "Bill Gates", "email": "retwqsd@gmail.com", "rate":0.3, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 1, "name": "Elon Musk", "email": "manukyaneghishe@gmail.com", "rate":0.1, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 2, "name": "Jeff Bezos", "email": "dfgfgdfg@gmail.com", "rate":0.01, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 3, "name": "Mark Zuckemberg", "email": "yuttrdgdf@gmail.com", "rate":0.2, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 4, "name": "sdfsd ertert", "email": "retwqsd@gmail.com", "rate":0.3, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 1, "name": "uytyf uyti", "email": "manukyaneghishe@gmail.com", "rate":0.1, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 2, "name": "ERGH WEER", "email": "dfgfgdfg@gmail.com", "rate":0.01, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 3, "name": "Donald Trump", "email": "yuttrdgdf@gmail.com", "rate":0.2, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 4, "name": "Steve Jobs", "email": "retwqsd@gmail.com", "rate":0.3, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 1, "name": "Joe Biden", "email": "manukyaneghishe@gmail.com", "rate":0.1, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 2, "name": "Vladimir Putin", "email": "dfgfgdfg@gmail.com", "rate":0.01, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 3, "name": "Vladimir Zelenski", "email": "yuttrdgdf@gmail.com", "rate":0.2, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 4, "name": "Nikol Pashinyan", "email": "retwqsd@gmail.com", "rate":0.3, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 1, "name": "Ruben Meschian", "email": "manukyaneghishe@gmail.com", "rate":0.1, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 2, "name": "Hayk Abelyan", "email": "dfgfgdfg@gmail.com", "rate":0.01, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 3, "name": "Qrq Qrqoryan", "email": "yuttrdgdf@gmail.com", "rate":0.2, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 4, "name": "Kim Kardashyan", "email": "retwqsd@gmail.com", "rate":0.3, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 1, "name": "Dan Bilzeryan", "email": "manukyaneghishe@gmail.com", "rate":0.1, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 2, "name": "Alexis Ohanyan", "email": "dfgfgdfg@gmail.com", "rate":0.01, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 3, "name": "Sharl Aznavour", "email": "yuttrdgdf@gmail.com", "rate":0.2, "image":"https://via.placeholder.com/500/92/92c952"},
   {"id": 4, "name": "Share", "email": "retwqsd@gmail.com", "rate":0.3, "image":"https://via.placeholder.com/500/92/92c952"},
  
];